workflows:
  ios-workflow:
    name: iOS Build MyNoleggio
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      # Build senza code signing (solo per test compilazione)
      # Per IPA installabile, aggiungi sezione ios_signing e certificati
      
      # Variabili d'ambiente
      vars:
        XCODE_PROJECT: "MyNoleggioApp.xcodeproj"
        XCODE_SCHEME: "MyNoleggioApp"
        BUNDLE_ID: "com.mynoleggioapp.app"  # CAMBIA CON IL TUO BUNDLE ID
      
      # Versione Xcode da usare
      xcode: latest
      cocoapods: default
    
    # Script da eseguire in sequenza
    scripts:
      - name: Verifica ambiente build
        script: |
          echo "🔍 Verifica ambiente..."
          xcode-select --print-path
          xcodebuild -version
          ls -la
      
      - name: Verifica progetto Xcode
        script: |
          echo "📱 Verifica progetto Xcode..."
          xcodebuild -list -project "$XCODE_PROJECT"
      
      - name: Installa dipendenze (se necessario)
        script: |
          # Se usi CocoaPods, decommentare:
          # pod install
          echo "✅ Nessuna dipendenza da installare"
      
      - name: Incrementa build number (opzionale)
        script: |
          # Incrementa automaticamente il build number
          cd MyNoleggioApp
          BUILD_NUMBER=$(($(grep -m1 'CFBundleVersion' Info.plist | sed 's/[^0-9]*//g') + 1))
          echo "📦 Nuovo build number: $BUILD_NUMBER"
          # /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" Info.plist
      
      - name: Build senza firma (solo test compilazione)
        script: |
          echo "🚀 Build per simulatore..."
          xcodebuild -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            clean build
    
    # File generati da conservare
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app.dSYM
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.ipa
    
    # Opzioni di pubblicazione
    publishing:
      # Email di notifica
      email:
        recipients:
          - denis.demonte@gmail.com  # CAMBIA CON LA TUA EMAIL
        notify:
          success: true
          failure: true
      
      # Opzionale: pubblicazione su App Store Connect/TestFlight
      # app_store_connect:
      #   api_key: $APP_STORE_CONNECT_PRIVATE_KEY
      #   key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
      #   issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      #   submit_to_testflight: true
      
      # Opzionale: pubblicazione su Slack
      # slack:
      #   channel: '#builds'
      #   notify_on_build_start: false
      #   notify:
      #     success: true
      #     failure: true

